variables:

  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
#change ip


image: maven:latest

stages:
  - build
#  - test
  - package
  - deploy

cache:
  paths:
    - .m2/repository
    - target

#before_script:
#  - cd ./integrador_v0.1    
#  - mvn -f  pom.xml


build_job:
  stage: build
  script:
    - echo "Maven compile started"
    - cd ./integrador_v0.1
    - mvn compile

#test_job:
#  stage: test
#  script:
#    - echo "Maven test started"
#    - cd ./integrador_v0.1
#    - mvn clean test
#esto es una prueba

package_job: 
  stage: package
  artifacts:
    paths:
    - integrador_v0.1/target/*.jar
  script:
    - cd ./integrador_v0.1 
    - mvn package

deploy_job: 
  stage: deploy 
  image: alpine:3.11 
  before_script: 
    - apk update && apk add openssh-client bash 
    - mkdir -p ~/.ssh 
    - eval $(ssh-agent -s) 
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null 
    - touch ~/.ssh/config 
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config 
    - ssh-keyscan -H $DEPLOY_TEST_ID >> ~/.ssh/known_hosts 
  script: 
    - ssh ubuntu@$DEPLOY_TEST_ID "sudo apt install openjdk-8-jdk -y" 
    - ssh ubuntu@$DEPLOY_TEST_ID "sudo systemctl stop ubicarapp.service" 
    - scp ./integrador_v0.1/target/integrador_v0.1-0.0.1-SNAPSHOT.jar ubuntu@$DEPLOY_TEST_ID:~/ubicar-app/ 
    - ssh ubuntu@$DEPLOY_TEST_ID "sudo systemctl start ubicarapp.service"
